server:
  port: 8081
spring:
  application :
    name: auth-service


eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8762/eureka
    fetch-registry: true
  instance:
    hostname: localhost
    prefer-ip-address: true
    lease-renewal-interval-in-seconds: 10
    lease-expiration-duration-in-seconds: 20

security:
  jwt:
    signing-key: should-be-externally-configured