server:
  port: 8027
spring:
  application :
    name: account-service
  data:
    cassandra:
      keyspace-name: sp_cloud_account
      contact-points: localhost
      port: 9042
      schema-action: NONE   #create_if_not_exists

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8762/eureka
    fetch-registry: true
  instance:
    hostname: localhost
    prefer-ip-address: true
    lease-renewal-interval-in-seconds: 10
    lease-expiration-duration-in-seconds: 20